# Generated by Django 5.1.14 on 2025-12-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0008_organizationmember_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("credits", models.IntegerField()),
                ("price_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rate_per_credit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per credit in INR",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_credit_package",
                "ordering": ["credits"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("scale", "Scale"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                    ),
                ),
                (
                    "price_inr",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in INR", max_digits=10
                    ),
                ),
                (
                    "credits_per_month",
                    models.IntegerField(help_text="Credits allocated per month"),
                ),
                (
                    "effective_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Effective rate per credit",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "storage_gb",
                    models.IntegerField(default=5, help_text="Free storage in GB"),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True,
                        help_text="Max users allowed (null = unlimited)",
                        null=True,
                    ),
                ),
                ("priority_support", models.BooleanField(default=False)),
                ("api_access", models.BooleanField(default=True)),
                (
                    "credit_rollover",
                    models.BooleanField(
                        default=True, help_text="Allow unused credits to rollover"
                    ),
                ),
                (
                    "max_rollover_months",
                    models.IntegerField(
                        default=1, help_text="Max months to rollover credits"
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription_plan",
                "ordering": ["price_inr"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("2d_image", "2D Image"),
                            ("3d_volume", "3D Volume"),
                            ("time_series", "Time Series"),
                            ("video", "Video"),
                            ("3d_annotation", "3D Annotation"),
                            ("signal_data", "Signal Data"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        help_text="e.g., X-ray (Chest), CT Scan, ECG", max_length=100
                    ),
                ),
                ("base_credit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_description",
                    models.CharField(
                        help_text="e.g., per image, per slice, per minute",
                        max_length=100,
                    ),
                ),
                (
                    "classification_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bounding_box_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "segmentation_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "keypoint_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "polygon_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "time_sequence_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "billing_annotation_pricing",
                "unique_together": {("data_type", "modality")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("next_billing_date", models.DateTimeField()),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("credits_allocated_this_month", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_for",
                    models.CharField(
                        choices=[
                            ("credits", "Credit Package"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=100, unique=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
                ("razorpay_signature", models.CharField(blank=True, max_length=255)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.creditpackage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("payg", "Pay As You Go"),
                            ("subscription", "Subscription"),
                        ],
                        default="payg",
                        max_length=20,
                    ),
                ),
                (
                    "available_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "rollover_credits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Credits rolled over from previous month",
                        max_digits=15,
                    ),
                ),
                (
                    "storage_used_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_storage_check", models.DateTimeField(blank=True, null=True)),
                ("razorpay_customer_id", models.CharField(blank=True, max_length=100)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("billing_address", models.TextField(blank=True)),
                (
                    "gstin",
                    models.CharField(
                        blank=True, help_text="GST Identification Number", max_length=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="organizations.organization",
                    ),
                ),
                (
                    "active_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_orgs",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_organization_billing",
            },
        ),
        migrations.CreateModel(
            name="AnnotatorEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "inr_equivalent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "revenue_share_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=45.0,
                        help_text="Percentage of credits annotator receives",
                        max_digits=5,
                    ),
                ),
                ("total_annotations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_earnings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_annotator_earnings",
                "unique_together": {("annotator", "organization")},
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("subscription", "Subscription Allocation"),
                            ("annotation", "Annotation Cost"),
                            ("storage", "Storage Cost"),
                            ("refund", "Refund"),
                            ("rollover", "Credit Rollover"),
                            ("bonus", "Bonus Credits"),
                        ],
                        default="annotation",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction details",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_credit_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="billing_cre_organiz_c7e5f0_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "category"],
                        name="billing_cre_transac_2e0a0c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_month",
                    models.DateField(help_text="First day of billing month"),
                ),
                (
                    "storage_used_gb",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "free_storage_gb",
                    models.DecimalField(decimal_places=2, default=5, max_digits=10),
                ),
                (
                    "billable_storage_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "credits_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="1 credit per GB per month",
                        max_digits=10,
                    ),
                ),
                ("is_charged", models.BooleanField(default=False)),
                ("charged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_billing",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_storage_billing",
                "ordering": ["-billing_month"],
                "unique_together": {("organization", "billing_month")},
            },
        ),
    ]





