# Generated by Django 5.1.14 on 2026-01-02 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("organizations", "0008_organizationmember_role"),
        ("projects", "0035_alter_project_auto_assign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased (Never expires)"),
                            ("bonus", "Bonus (90 days)"),
                            ("rollover", "Rollover (30 days)"),
                            ("promotional", "Promotional (Custom)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("remaining", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null for never-expiring credits",
                        null=True,
                    ),
                ),
                ("is_expired", models.BooleanField(default=False)),
                (
                    "expired_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_expiries",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_credit_expiry",
                "ordering": ["expires_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_deposit_required",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Security deposit required for this project",
                        max_digits=15,
                    ),
                ),
                (
                    "security_deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Security deposit actually paid",
                        max_digits=15,
                    ),
                ),
                (
                    "security_deposit_refunded",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Security deposit refunded",
                        max_digits=15,
                    ),
                ),
                ("deposit_paid_at", models.DateTimeField(blank=True, null=True)),
                ("deposit_refunded_at", models.DateTimeField(blank=True, null=True)),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                (
                    "storage_used_gb",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "last_storage_calculated",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "estimated_annotation_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "actual_annotation_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credits_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant (No activity 30 days)"),
                            ("warning", "Warning (Low credits)"),
                            ("grace", "Grace Period (Credits exhausted)"),
                            ("deleted", "Deleted"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("state_changed_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                ("last_export_at", models.DateTimeField(blank=True, null=True)),
                ("export_count", models.IntegerField(default=0)),
                ("dormant_since", models.DateTimeField(blank=True, null=True)),
                ("warning_sent_at", models.DateTimeField(blank=True, null=True)),
                ("grace_period_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_deletion_at", models.DateTimeField(blank=True, null=True)),
                ("is_deposit_held", models.BooleanField(default=False)),
                ("is_exportable", models.BooleanField(default=True)),
                ("export_blocked_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "billing_project_billing",
            },
        ),
        migrations.CreateModel(
            name="ProjectBillingStateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(max_length=20)),
                ("to_state", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_logs",
                        to="billing.projectbilling",
                    ),
                ),
            ],
            options={
                "db_table": "billing_project_state_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "storage_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "annotation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_deposit", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("held", "Held"),
                            ("partially_used", "Partially Used"),
                            ("refunded", "Refunded"),
                            ("forfeited", "Forfeited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "amount_forfeited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("forfeited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_deposits",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_deposits",
                        to="billing.credittransaction",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_deposits",
                        to="projects.project",
                    ),
                ),
                (
                    "refund_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_refunds",
                        to="billing.credittransaction",
                    ),
                ),
            ],
            options={
                "db_table": "billing_security_deposit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsageTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "read_requests",
                    models.IntegerField(
                        default=0, help_text="GET requests (list, retrieve)"
                    ),
                ),
                (
                    "write_requests",
                    models.IntegerField(
                        default=0, help_text="POST, PUT, PATCH requests"
                    ),
                ),
                (
                    "export_requests",
                    models.IntegerField(
                        default=0, help_text="Export/download requests"
                    ),
                ),
                ("free_read_limit", models.IntegerField(default=10000)),
                ("free_write_limit", models.IntegerField(default=1000)),
                ("free_export_limit", models.IntegerField(default=100)),
                ("read_overage", models.IntegerField(default=0)),
                ("write_overage", models.IntegerField(default=0)),
                ("export_overage", models.IntegerField(default=0)),
                (
                    "credits_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("charged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_api_usage",
                "ordering": ["-date"],
                "unique_together": {("organization", "date")},
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_format", models.CharField(max_length=50)),
                ("tasks_exported", models.IntegerField(default=0)),
                ("annotations_exported", models.IntegerField(default=0)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "credits_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "is_free_export",
                    models.BooleanField(
                        default=False, help_text="First export is free"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_records",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "billing_export_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="billing_exp_project_2aed72_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="billing_exp_organiz_f9992e_idx",
                    ),
                ],
            },
        ),
    ]





