# Generated by Django 5.1.15 on 2026-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_project_billing_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagebilling",
            name="billing_type",
            field=models.CharField(default="payg", max_length=20),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Discount amount", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage applied from subscription",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount before discount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Final amount after discount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="rate_per_gb",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Rate per GB per month applied",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="storagebilling",
            name="subscription_plan_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="annotation_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage on annotation costs",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="annual_bonus_credits",
            field=models.IntegerField(
                default=0, help_text="Bonus credits for annual subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="annual_bonus_months",
            field=models.IntegerField(
                default=0,
                help_text="Number of free months for annual plan (e.g., 2 = pay for 10, get 12)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(
                blank=True, help_text="Plan description for display to users"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="extra_storage_rate_per_gb",
            field=models.DecimalField(
                decimal_places=2,
                default=15.0,
                help_text="Rate per GB per month for storage beyond free limit (in INR)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features_json",
            field=models.JSONField(
                default=list, help_text="List of features for display"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_projects",
            field=models.IntegerField(
                default=3,
                help_text="Maximum number of active projects allowed (0 = unlimited)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="renewal_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount for existing subscribers renewing",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage on extra storage charges",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="storagebilling",
            name="credits_charged",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Credits deducted from balance",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("none", "No Billing Cycle (PAYG)"),
                    ("monthly", "Monthly"),
                    ("annual", "Annual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("payg", "Pay As You Go"),
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                    ("scale", "Scale"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=20,
            ),
        ),
    ]
