# Generated by Django 5.1.15 on 2026-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_rename_security_deposit_to_project_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectbilling",
            name="annotation_completed",
            field=models.BooleanField(
                default=False, help_text="Whether annotation work is completed"
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="annotation_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When annotation work was marked completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="current_billing_cycle_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of current monthly billing cycle",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="insufficient_credits_warned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When user was warned about insufficient credits for retention",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="last_retention_charged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last retention fee was charged",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="months_retained",
            field=models.IntegerField(
                default=0,
                help_text="Number of months the project has been retained after annotation completion",
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="next_retention_charge_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next monthly retention charge is due",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="retention_billing_started",
            field=models.BooleanField(
                default=False, help_text="Whether monthly retention billing has started"
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="retention_deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When project will be deleted due to unpaid retention (3 weeks after warning)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="retention_warning_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the retention warning was sent (7 days before charge)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="storage_fee_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Storage overage fee paid at project creation (non-refundable)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="storage_overage_gb",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Storage exceeding free limit at project creation",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="projectbilling",
            name="total_retention_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total retention charges paid over project lifetime",
                max_digits=15,
            ),
        ),
    ]
