# Generated by Django 5.1.14 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0060_add_allow_skip_to_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignment_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this task has been assigned"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="complexity",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                help_text="Task complexity level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_time",
            field=models.IntegerField(
                default=300, help_text="Estimated time to complete in seconds"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("normal", "Normal"),
                    ("low", "Low"),
                ],
                default="normal",
                help_text="Task priority level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="required_trust_level",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("junior", "Junior"),
                    ("regular", "Regular"),
                    ("senior", "Senior"),
                    ("expert", "Expert"),
                ],
                default="new",
                help_text="Minimum trust level required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="target_assignment_count",
            field=models.IntegerField(
                default=1, help_text="Target number of assignments for this task"
            ),
        ),
    ]





