# Generated by Django 5.1.14 on 2026-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_assignment_count_task_complexity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="overlap",
            field=models.IntegerField(
                db_index=True,
                default=3,
                help_text="Number of distinct annotators required for consensus (default: 3)",
                verbose_name="overlap",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="target_assignment_count",
            field=models.IntegerField(
                default=3,
                help_text="Target number of assignments for consensus (default: 3)",
            ),
        ),
    ]





