# Generated by Django 5.1.15 on 2026-01-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0062_add_annotator_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failedprediction",
            name="model_version",
        ),
    ]
