# Generated by Django 5.1.15 on 2026-01-18 06:01

import core.utils.common
from django.db import migrations, models


def generate_unique_api_keys(apps, schema_editor):
    """Generate unique API keys for each existing organization."""
    Organization = apps.get_model('organizations', 'Organization')
    for org in Organization.objects.all():
        org.api_key = core.utils.common.create_hash()
        org.save(update_fields=['api_key'])


def reverse_api_keys(apps, schema_editor):
    """Reverse: set all API keys to None."""
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.all().update(api_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organizationmember_role"),
    ]

    operations = [
        # Step 1: Add api_key field WITHOUT unique constraint first
        migrations.AddField(
            model_name="organization",
            name="api_key",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=64,
                help_text="API key for SDK/programmatic access. Only visible to admins and owners.",
                verbose_name="api key",
            ),
        ),
        # Step 2: Add api_key_created_at field
        migrations.AddField(
            model_name="organization",
            name="api_key_created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the API key was created or last reset.",
                null=True,
                verbose_name="api key created at",
            ),
        ),
        # Step 3: Run data migration to generate unique keys for existing orgs
        migrations.RunPython(generate_unique_api_keys, reverse_api_keys),
        # Step 4: Now add the unique constraint
        migrations.AlterField(
            model_name="organization",
            name="api_key",
            field=models.CharField(
                blank=True,
                default=core.utils.common.create_hash,
                help_text="API key for SDK/programmatic access. Only visible to admins and owners.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="api key",
            ),
        ),
    ]
