# Generated by Django 5.1.14 on 2025-12-27 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
        ("tasks", "0060_add_allow_skip_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Email Verification"),
                            ("pending_test", "Pending Test"),
                            ("test_submitted", "Test Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending_verification",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="List of annotation skills"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Languages spoken"),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Brief introduction")),
                ("total_tasks_completed", models.IntegerField(default=0)),
                (
                    "accuracy_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cached metric, updated asynchronously",
                        max_digits=5,
                    ),
                ),
                (
                    "average_time_per_task",
                    models.IntegerField(
                        default=0, help_text="Average seconds per task"
                    ),
                ),
                (
                    "rejection_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "pending_approval",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("account_holder_name", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "verification_token_created",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Profile",
                "verbose_name_plural": "Annotator Profiles",
                "db_table": "annotator_profile",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_type", models.CharField(default="general", max_length=50)),
                (
                    "test_tasks",
                    models.JSONField(
                        default=list, help_text="List of task IDs or test data"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "annotations",
                    models.JSONField(default=dict, help_text="Annotator test results"),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        default=dict, help_text="Detailed scoring breakdown"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "annotation_test",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "in_progress"])),
                        fields=("annotator",),
                        name="one_active_test_per_annotator",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("annotator", "Annotator"), ("reviewer", "Reviewer")],
                        default="annotator",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("assigned_by", models.CharField(default="system", max_length=50)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_tasks",
                    models.IntegerField(
                        default=0, help_text="Cached count, updated via signals"
                    ),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(
                        default=0, help_text="Total tasks completed in this project"
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Assignment",
                "verbose_name_plural": "Project Assignments",
                "db_table": "project_assignment",
                "ordering": ["-assigned_at"],
                "unique_together": {("project", "annotator")},
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "annotation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_assignment",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_assignments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Assignment",
                "verbose_name_plural": "Task Assignments",
                "db_table": "task_assignment",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["annotator", "status"],
                        name="task_assign_annotat_874c2d_idx",
                    ),
                    models.Index(
                        fields=["task"], name="task_assign_task_id_b36aa9_idx"
                    ),
                ],
                "unique_together": {("annotator", "task")},
            },
        ),
    ]





