# Generated by Django 5.1.14 on 2025-12-28 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotatorprofile",
            name="status",
            field=models.CharField(default="pending_verification", max_length=32),
        ),
        migrations.AlterField(
            model_name="annotatorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="annotatorprofile",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="annotatorprofile",
            name="verification_token_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]





