# Generated by Django 5.1.14 on 2025-12-30 13:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0003_alter_annotatorprofile_user"),
        ("tasks", "0060_add_allow_skip_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                            ("withdrawal", "Withdrawal"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "earning_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediate", "Immediate (40%)"),
                            ("consensus", "Consensus (40%)"),
                            ("review", "Review (20%)"),
                            ("full", "Full Payment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Earnings Transaction",
                "verbose_name_plural": "Earnings Transactions",
                "db_table": "earnings_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HoneypotTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ground_truth",
                    models.JSONField(help_text="Expected annotation result"),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.8,
                        help_text="Minimum agreement for pass (0-1)",
                        max_digits=5,
                    ),
                ),
                ("times_shown", models.IntegerField(default=0)),
                ("times_passed", models.IntegerField(default=0)),
                ("times_failed", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Honeypot Task",
                "verbose_name_plural": "Honeypot Tasks",
                "db_table": "honeypot_task",
            },
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[("bank_transfer", "Bank Transfer"), ("upi", "UPI")],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "bank_details",
                    models.JSONField(
                        default=dict, help_text="Bank details at time of request"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("failure_reason", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payout Request",
                "verbose_name_plural": "Payout Requests",
                "db_table": "payout_request",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("junior", "Junior"),
                            ("regular", "Regular"),
                            ("senior", "Senior"),
                            ("expert", "Expert"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.8"), max_digits=4
                    ),
                ),
                ("tasks_completed", models.IntegerField(default=0)),
                (
                    "accuracy_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "honeypot_pass_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_honeypots", models.IntegerField(default=0)),
                ("passed_honeypots", models.IntegerField(default=0)),
                ("fraud_flags", models.IntegerField(default=0)),
                ("last_fraud_check", models.DateTimeField(blank=True, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("suspension_reason", models.TextField(blank=True)),
                ("level_updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trust Level",
                "verbose_name_plural": "Trust Levels",
                "db_table": "annotator_trust_level",
            },
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="base_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Base rate × complexity",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="consensus_agreement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Agreement with other annotators",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="consensus_payment",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="consensus_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="flagged_for_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="honeypot_passed",
            field=models.BooleanField(
                blank=True, help_text="Did annotator pass the honeypot?", null=True
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="immediate_payment",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="immediate_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="is_honeypot",
            field=models.BooleanField(
                default=False, help_text="Was this a honeypot task?"
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="quality_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Quality score multiplier",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="quality_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100 quality score",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="review_payment",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="review_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="time_spent_seconds",
            field=models.IntegerField(default=0, help_text="Time spent on annotation"),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="trust_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Trust level multiplier",
                max_digits=4,
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["status", "immediate_released"],
                name="task_assign_status_a8c7e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["status", "consensus_released"],
                name="task_assign_status_d5fe3f_idx",
            ),
        ),
        migrations.AddField(
            model_name="earningstransaction",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earnings_transactions",
                to="annotators.annotatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="earningstransaction",
            name="task_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="annotators.taskassignment",
            ),
        ),
        migrations.AddField(
            model_name="honeypottask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_honeypots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="honeypottask",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="honeypot_config",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="annotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout_requests",
                to="annotators.annotatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="earningstransaction",
            name="payout_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="annotators.payoutrequest",
            ),
        ),
        migrations.AddField(
            model_name="trustlevel",
            name="annotator",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_level",
                to="annotators.annotatorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="earningstransaction",
            index=models.Index(
                fields=["annotator", "-created_at"],
                name="earnings_tr_annotat_8d37ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="earningstransaction",
            index=models.Index(
                fields=["transaction_type"], name="earnings_tr_transac_fff032_idx"
            ),
        ),
    ]





