# Generated by Django 5.1.14 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0004_payment_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatorprofile",
            name="available_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Days available for work (e.g., ["Monday", "Tuesday"])',
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="excluded_task_types",
            field=models.JSONField(
                blank=True, default=list, help_text="Task types to exclude"
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="is_accepting_work",
            field=models.BooleanField(
                default=True, help_text="Whether annotator is accepting new work"
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="max_concurrent_tasks",
            field=models.IntegerField(
                default=5, help_text="Maximum number of concurrent tasks"
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="preferred_complexity",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                help_text="Preferred task complexity level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="preferred_hours_per_week",
            field=models.IntegerField(
                default=20, help_text="Preferred working hours per week"
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="preferred_task_types",
            field=models.JSONField(
                blank=True, default=list, help_text="Preferred task types"
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="timezone",
            field=models.CharField(
                default="UTC", help_text="Timezone for availability", max_length=50
            ),
        ),
    ]





