# Generated by Django 5.1.14 on 2026-01-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0005_annotatorprofile_available_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="available_days",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="excluded_task_types",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="is_accepting_work",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="max_concurrent_tasks",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="preferred_complexity",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="preferred_hours_per_week",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="preferred_task_types",
        ),
        migrations.RemoveField(
            model_name="annotatorprofile",
            name="timezone",
        ),
    ]





