# Generated by Django 5.1.14 on 2026-01-02 06:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0006_remove_annotatorprofile_available_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("volume", "Volume"),
                            ("quality", "Quality"),
                            ("streak", "Streak"),
                            ("speed", "Speed"),
                            ("special", "Special"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                            ("diamond", "Diamond"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("badge_icon", models.CharField(blank=True, max_length=100)),
                (
                    "requirement_type",
                    models.CharField(
                        help_text="e.g., tasks_completed, accuracy_score", max_length=50
                    ),
                ),
                (
                    "requirement_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_repeatable",
                    models.BooleanField(
                        default=False, help_text="Can be earned multiple times"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievement",
                "ordering": ["category", "tier"],
            },
        ),
        migrations.CreateModel(
            name="BonusPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("daily_top", "Daily Top Performers"),
                            ("weekly_top", "Weekly Top Performers"),
                            ("quality_bonus", "Quality Bonus Pool"),
                            ("referral", "Referral Bonus"),
                            ("special_event", "Special Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount_distributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "distribution_rules",
                    models.JSONField(
                        default=dict, help_text="JSON rules for distribution"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bonus Pool",
                "verbose_name_plural": "Bonus Pools",
                "db_table": "bonus_pool",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SkillBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("annotation_type", models.CharField(max_length=50)),
                ("required_tasks", models.IntegerField(default=100)),
                (
                    "required_accuracy",
                    models.DecimalField(decimal_places=2, default=85, max_digits=5),
                ),
                (
                    "skill_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.15"), max_digits=4
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill Badge",
                "verbose_name_plural": "Skill Badges",
                "db_table": "skill_badge",
            },
        ),
        migrations.CreateModel(
            name="AnnotatorStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("tasks_this_week", models.IntegerField(default=0)),
                ("week_start_date", models.DateField(blank=True, null=True)),
                ("tasks_this_month", models.IntegerField(default=0)),
                ("month_start_date", models.DateField(blank=True, null=True)),
                (
                    "total_streak_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Streak",
                "verbose_name_plural": "Annotator Streaks",
                "db_table": "annotator_streak",
            },
        ),
        migrations.CreateModel(
            name="BonusDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(max_length=255)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Performance metrics used for distribution",
                    ),
                ),
                ("distributed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_distributions",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="annotators.bonuspool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus Distribution",
                "verbose_name_plural": "Bonus Distributions",
                "db_table": "bonus_distribution",
                "ordering": ["-distributed_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotatorAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("times_earned", models.IntegerField(default=1)),
                (
                    "bonus_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="annotators.achievement",
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Achievement",
                "verbose_name_plural": "Annotator Achievements",
                "db_table": "annotator_achievement",
                "unique_together": {("annotator", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="DailyLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("tasks_completed", models.IntegerField(default=0)),
                (
                    "earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quality_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "leaderboard_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Leaderboard",
                "verbose_name_plural": "Daily Leaderboards",
                "db_table": "daily_leaderboard",
                "ordering": ["date", "rank"],
                "indexes": [
                    models.Index(
                        fields=["date", "-tasks_completed"],
                        name="daily_leade_date_4effe0_idx",
                    ),
                    models.Index(
                        fields=["date", "-earnings"], name="daily_leade_date_a29a34_idx"
                    ),
                ],
                "unique_together": {("date", "annotator")},
            },
        ),
        migrations.CreateModel(
            name="AnnotatorSkillBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tasks_completed", models.IntegerField(default=0)),
                (
                    "current_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_earned", models.BooleanField(default=False)),
                ("earned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_badges",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "skill_badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="annotators.skillbadge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Skill Badge",
                "verbose_name_plural": "Annotator Skill Badges",
                "db_table": "annotator_skill_badge",
                "unique_together": {("annotator", "skill_badge")},
            },
        ),
    ]





