# Generated by Django 5.1.14 on 2026-01-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0007_gamification_models"),
        ("tasks", "0061_task_assignment_count_task_complexity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskConsensus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_consensus", "In Consensus"),
                            ("consensus_reached", "Consensus Reached"),
                            ("conflict", "Conflict"),
                            ("review_required", "Review Required"),
                            ("finalized", "Finalized"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "consolidated_result",
                    models.JSONField(
                        blank=True,
                        help_text="The merged/consolidated annotation result",
                        null=True,
                    ),
                ),
                (
                    "required_annotations",
                    models.IntegerField(
                        default=1,
                        help_text="Number of annotations required for consensus",
                    ),
                ),
                (
                    "current_annotations",
                    models.IntegerField(
                        default=0, help_text="Current number of completed annotations"
                    ),
                ),
                (
                    "average_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average pairwise agreement score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "min_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum pairwise agreement",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum pairwise agreement",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "consolidation_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used for consolidation (voting, union, intersection, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consensus_reached_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_consensus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Consensus",
                "verbose_name_plural": "Task Consensus Records",
                "db_table": "task_consensus",
            },
        ),
        migrations.CreateModel(
            name="ConsensusQualityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2, help_text="0-100 quality score", max_digits=5
                    ),
                ),
                (
                    "label_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "position_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "completeness_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avg_peer_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average agreement with other annotators",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "quality_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier applied to consensus payment",
                        max_digits=4,
                    ),
                ),
                ("consensus_payment_released", models.BooleanField(default=False)),
                (
                    "consensus_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_scores",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "task_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_quality",
                        to="annotators.taskassignment",
                    ),
                ),
                (
                    "task_consensus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_scores",
                        to="annotators.taskconsensus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consensus Quality Score",
                "verbose_name_plural": "Consensus Quality Scores",
                "db_table": "consensus_quality_score",
            },
        ),
        migrations.CreateModel(
            name="AnnotatorAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreement_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100 agreement score",
                        max_digits=5,
                    ),
                ),
                (
                    "iou_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="IoU for bounding boxes/polygons",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "label_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Label matching score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "position_agreement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Position/coordinate agreement",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("annotation_type", models.CharField(blank=True, max_length=50)),
                (
                    "comparison_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed comparison breakdown",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_first",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "annotator_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_second",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "assignment_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_first",
                        to="annotators.taskassignment",
                    ),
                ),
                (
                    "assignment_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_second",
                        to="annotators.taskassignment",
                    ),
                ),
                (
                    "task_consensus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="annotators.taskconsensus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Agreement",
                "verbose_name_plural": "Annotator Agreements",
                "db_table": "annotator_agreement",
            },
        ),
        migrations.AddIndex(
            model_name="taskconsensus",
            index=models.Index(fields=["status"], name="task_consen_status_f02fe8_idx"),
        ),
        migrations.AddIndex(
            model_name="taskconsensus",
            index=models.Index(
                fields=["task", "status"], name="task_consen_task_id_586a71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consensusqualityscore",
            index=models.Index(
                fields=["annotator", "quality_score"],
                name="consensus_q_annotat_87f057_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consensusqualityscore",
            index=models.Index(
                fields=["task_consensus"], name="consensus_q_task_co_e59909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotatoragreement",
            index=models.Index(
                fields=["task_consensus"], name="annotator_a_task_co_fce164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotatoragreement",
            index=models.Index(
                fields=["annotator_1", "agreement_score"],
                name="annotator_a_annotat_d58793_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotatoragreement",
            index=models.Index(
                fields=["annotator_2", "agreement_score"],
                name="annotator_a_annotat_bf9b43_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotatoragreement",
            unique_together={("task_consensus", "annotator_1", "annotator_2")},
        ),
    ]





