# Generated by Django 5.1.14 on 2026-01-04 19:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0008_add_consensus_models"),
        ("projects", "0035_alter_project_auto_assign"),
        ("tasks", "0061_task_assignment_count_task_complexity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "expertise_level",
                    models.CharField(
                        choices=[
                            ("junior_expert", "Junior Expert"),
                            ("senior_expert", "Senior Expert"),
                            ("lead_expert", "Lead Expert"),
                        ],
                        default="junior_expert",
                        max_length=20,
                    ),
                ),
                (
                    "expertise_areas",
                    models.JSONField(
                        default=list,
                        help_text="List of annotation types expert can review (classification, bounding_box, etc.)",
                    ),
                ),
                ("total_reviews_completed", models.IntegerField(default=0)),
                ("total_approvals", models.IntegerField(default=0)),
                ("total_rejections", models.IntegerField(default=0)),
                ("total_corrections", models.IntegerField(default=0)),
                (
                    "average_review_time",
                    models.IntegerField(
                        default=0, help_text="Average seconds per review"
                    ),
                ),
                (
                    "correction_accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="How often their corrections match ground truth",
                        max_digits=5,
                    ),
                ),
                (
                    "consistency_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Consistency across similar reviews",
                        max_digits=5,
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "pending_payout",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("account_holder_name", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "max_reviews_per_day",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum reviews this expert can handle per day",
                    ),
                ),
                (
                    "current_workload",
                    models.IntegerField(
                        default=0, help_text="Current number of pending reviews"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experts_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Profile",
                "verbose_name_plural": "Expert Profiles",
                "db_table": "expert_profile",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertPayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(default="bank_transfer", max_length=20),
                ),
                (
                    "bank_details",
                    models.JSONField(
                        default=dict, help_text="Snapshot of bank details"
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("failure_reason", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_expert_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to="annotators.expertprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Payout Request",
                "verbose_name_plural": "Expert Payout Requests",
                "db_table": "expert_payout_request",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "review_all_tasks",
                    models.BooleanField(
                        default=False,
                        help_text="If true, expert reviews all tasks, not just conflicts",
                    ),
                ),
                (
                    "sample_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="Percentage of conflict tasks to assign to this expert",
                        max_digits=5,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority experts get tasks first"
                    ),
                ),
                ("tasks_reviewed", models.IntegerField(default=0)),
                ("tasks_approved", models.IntegerField(default=0)),
                ("tasks_rejected", models.IntegerField(default=0)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_project_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="annotators.expertprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Project Assignment",
                "verbose_name_plural": "Expert Project Assignments",
                "db_table": "expert_project_assignment",
                "ordering": ["-priority", "-assigned_at"],
                "unique_together": {("expert", "project")},
            },
        ),
        migrations.CreateModel(
            name="ExpertReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected - Needs Rework"),
                            ("corrected", "Corrected by Expert"),
                            ("escalated", "Escalated to Lead"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_reason",
                    models.CharField(
                        default="disagreement",
                        help_text="Why this task was assigned (disagreement, random_sample, manual)",
                        max_length=50,
                    ),
                ),
                (
                    "disagreement_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Disagreement score that triggered review",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low_quality", "Low Quality Annotations"),
                            ("disagreement", "High Annotator Disagreement"),
                            ("incorrect_labels", "Incorrect Labels"),
                            ("incomplete", "Incomplete Annotation"),
                            ("ambiguous", "Ambiguous Data - Skip"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "corrected_result",
                    models.JSONField(
                        blank=True,
                        help_text="Expert's corrected annotation result",
                        null=True,
                    ),
                ),
                (
                    "correction_summary",
                    models.TextField(
                        blank=True, help_text="Summary of what was corrected"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("review_time_seconds", models.IntegerField(default=0)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_released", models.BooleanField(default=False)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to="annotators.expertprofile",
                    ),
                ),
                (
                    "project_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to="annotators.expertprojectassignment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="tasks.task",
                    ),
                ),
                (
                    "task_consensus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="annotators.taskconsensus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Review Task",
                "verbose_name_plural": "Expert Review Tasks",
                "db_table": "expert_review_task",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertEarningsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("review_payment", "Review Payment"),
                            ("correction_bonus", "Correction Bonus"),
                            ("quality_bonus", "Quality Bonus"),
                            ("withdrawal", "Withdrawal"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings_transactions",
                        to="annotators.expertprofile",
                    ),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="annotators.expertreviewtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Earnings Transaction",
                "verbose_name_plural": "Expert Earnings Transactions",
                "db_table": "expert_earnings_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="expertreviewtask",
            index=models.Index(
                fields=["expert", "status"], name="expert_revi_expert__0aff7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertreviewtask",
            index=models.Index(
                fields=["task", "status"], name="expert_revi_task_id_8a89e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertreviewtask",
            index=models.Index(
                fields=["status", "assigned_at"], name="expert_revi_status_2416cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expertreviewtask",
            unique_together={("expert", "task")},
        ),
        migrations.AddIndex(
            model_name="expertearningstransaction",
            index=models.Index(
                fields=["expert", "-created_at"], name="expert_earn_expert__5ec28a_idx"
            ),
        ),
    ]





