# Generated by Django 5.1.14 on 2026-01-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0009_add_expert_models"),
        ("projects", "0036_add_annotator_notification"),
        ("tasks", "0062_add_annotator_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotatorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("review_accepted", "Review Accepted"),
                            (
                                "review_rejected_reannotate",
                                "Review Rejected - Re-annotation Required",
                            ),
                            ("review_feedback", "Review Feedback"),
                            ("payment_released", "Payment Released"),
                            ("task_assigned", "Task Assigned"),
                            ("achievement_unlocked", "Achievement Unlocked"),
                            ("system_announcement", "System Announcement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotator_notifications",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotator_notifications",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Notification",
                "verbose_name_plural": "Annotator Notifications",
                "db_table": "annotator_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["annotator", "-created_at"],
                        name="annotator_n_annotat_ca4655_idx",
                    ),
                    models.Index(
                        fields=["annotator", "is_read"],
                        name="annotator_n_annotat_a14c5a_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="annotator_n_notific_9a7354_idx",
                    ),
                ],
            },
        ),
    ]





