# Generated by Django 5.1.14 on 2026-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0010_add_annotator_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="bank_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete bank details stored securely",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="custom_base_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom base rate override (if null, uses default rates)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="custom_level_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custom level multiplier override",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="last_payout_at",
            field=models.DateTimeField(
                blank=True, help_text="Last successful payout date", null=True
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="minimum_payout",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="Minimum payout threshold in INR",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("upi", "UPI"),
                    ("paypal", "PayPal"),
                ],
                default="bank_transfer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="total_payouts_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount paid out",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="total_payouts_count",
            field=models.IntegerField(
                default=0, help_text="Total number of payouts processed"
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="average_review_time",
            field=models.IntegerField(
                default=0, help_text="Average review time in seconds"
            ),
        ),
    ]





