# Generated by Django 5.1.14 on 2026-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0012_add_accuracy_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="annotatorperformancehistory",
            new_name="annotator_p_annotat_ee32be_idx",
            old_name="annotator_p_annotat_7b8c12_idx",
        ),
        migrations.RenameIndex(
            model_name="annotatorperformancehistory",
            new_name="annotator_p_metric__d58fe4_idx",
            old_name="annotator_p_metric__a4e3f2_idx",
        ),
        migrations.AlterField(
            model_name="annotatorperformancehistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]





