# Generated by Django 5.1.15 on 2026-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotators",
            "0013_rename_annotator_p_annotat_7b8c12_idx_annotator_p_annotat_ee32be_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotatoragreement",
            name="iou_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="IoU for bounding boxes/polygons (0-100)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annotatoragreement",
            name="label_agreement",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Label matching score (0-100)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annotatoragreement",
            name="position_agreement",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Position/coordinate agreement (0-100)",
                max_digits=7,
                null=True,
            ),
        ),
    ]
