# Generated by Django 5.1.15 on 2026-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0014_fix_decimal_field_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatorprofile",
            name="inactive_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When annotator was marked inactive due to prolonged absence",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="annotatorprofile",
            name="is_active_for_assignments",
            field=models.BooleanField(
                default=True,
                help_text="Whether annotator should receive new task assignments. Set to False when annotator is inactive for extended period.",
            ),
        ),
    ]
