# Generated by Django 5.1.15 on 2026-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0016_expert_assignment_engine_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="expertise_areas",
            field=models.JSONField(
                default=list,
                help_text="[ON HOLD] List of annotation types expert can review",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="max_concurrent_reviews",
            field=models.IntegerField(
                default=50,
                help_text="Maximum concurrent review tasks this expert can have",
            ),
        ),
    ]
