# Generated by Django 5.1.15 on 2026-02-06 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0017_alter_expertprofile_expertise_areas_and_more"),
        ("projects", "0039_remove_project_is_draft"),
        ("tasks", "0063_remove_failedprediction_model_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatorprofile",
            name="total_honeypots_evaluated",
            field=models.IntegerField(
                default=0, help_text="Total number of honeypot evaluations (lifetime)"
            ),
        ),
        migrations.AddField(
            model_name="trustlevel",
            name="rolling_accuracy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rolling window accuracy for warning decisions",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="GoldenStandardTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ground_truth",
                    models.JSONField(help_text="Verified correct annotation result"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("expert", "Expert Annotated"),
                            ("client", "Client Provided"),
                            ("admin", "Admin Curated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tolerance",
                    models.DecimalField(decimal_places=2, default=0.85, max_digits=3),
                ),
                ("times_shown", models.IntegerField(default=0)),
                ("times_passed", models.IntegerField(default=0)),
                ("times_failed", models.IntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("max_uses", models.IntegerField(default=100)),
                ("is_retired", models.BooleanField(default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_golden_standards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="golden_standards",
                        to="projects.project",
                    ),
                ),
                (
                    "source_annotation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original annotation this was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.annotation",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="golden_standard",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Golden Standard Task",
                "verbose_name_plural": "Golden Standard Tasks",
                "db_table": "golden_standard_task",
            },
        ),
        migrations.CreateModel(
            name="HoneypotAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_in_queue", models.IntegerField(default=0)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("annotator_result", models.JSONField(blank=True, null=True)),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("passed", models.BooleanField(null=True)),
                (
                    "evaluation_details",
                    models.JSONField(
                        blank=True, help_text="Detailed comparison breakdown", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("evaluated", "Evaluated"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honeypot_assignments",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "golden_standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="annotators.goldenstandardtask",
                    ),
                ),
                (
                    "task_assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honeypot_info",
                        to="annotators.taskassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Honeypot Assignment",
                "verbose_name_plural": "Honeypot Assignments",
                "db_table": "honeypot_assignment",
            },
        ),
        migrations.CreateModel(
            name="AccuracyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("honeypots_evaluated", models.IntegerField(default=0)),
                ("honeypots_passed", models.IntegerField(default=0)),
                (
                    "daily_average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_honeypots_lifetime", models.IntegerField(default=0)),
                (
                    "lifetime_accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="All-time accuracy at end of this day",
                        max_digits=5,
                    ),
                ),
                (
                    "rolling_accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rolling window accuracy at end of this day",
                        max_digits=5,
                    ),
                ),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honeypot_accuracy_history",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accuracy History",
                "verbose_name_plural": "Accuracy Histories",
                "db_table": "accuracy_history",
                "indexes": [
                    models.Index(
                        fields=["annotator", "date"],
                        name="accuracy_hi_annotat_fb0ea1_idx",
                    ),
                    models.Index(fields=["date"], name="accuracy_hi_date_13c239_idx"),
                ],
                "unique_together": {("annotator", "date")},
            },
        ),
        migrations.CreateModel(
            name="AnnotatorWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("soft_warning", "Soft Warning"),
                            ("formal_warning", "Formal Warning"),
                            ("final_warning", "Final Warning"),
                            ("suspension", "Suspension"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "accuracy_at_warning",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("message", models.TextField()),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honeypot_warnings",
                        to="annotators.annotatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Warning",
                "verbose_name_plural": "Annotator Warnings",
                "db_table": "annotator_warning",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["annotator", "warning_type"],
                        name="annotator_w_annotat_b19268_idx",
                    ),
                    models.Index(
                        fields=["warning_type", "created_at"],
                        name="annotator_w_warning_e10149_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="annotator_w_created_b82785_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="goldenstandardtask",
            index=models.Index(
                fields=["project", "is_active"], name="golden_stan_project_01418f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goldenstandardtask",
            index=models.Index(
                fields=["is_retired"], name="golden_stan_is_reti_5b6c79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honeypotassignment",
            index=models.Index(
                fields=["annotator", "status"], name="honeypot_as_annotat_d788c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honeypotassignment",
            index=models.Index(
                fields=["golden_standard", "status"],
                name="honeypot_as_golden__8d0944_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="honeypotassignment",
            index=models.Index(
                fields=["status", "assigned_at"], name="honeypot_as_status_3fcb9b_idx"
            ),
        ),
    ]
