# Generated by Django 5.1.15 on 2026-02-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0018_honeypot_system_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or class (e.g., 'image', 'mic', 'text')",
                        max_length=50,
                    ),
                ),
                (
                    "template_folder",
                    models.CharField(
                        blank=True,
                        help_text="Folder name in annotation_templates (e.g., 'computer-vision')",
                        max_length=100,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expertise Category",
                "verbose_name_plural": "Expertise Categories",
                "db_table": "expertise_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="annotationtest",
            name="expertise_category",
            field=models.CharField(
                blank=True,
                help_text="Selected expertise category (e.g., 'computer-vision')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="annotationtest",
            name="expertise_specialization",
            field=models.CharField(
                blank=True,
                help_text="Selected specialization (e.g., 'chest-x-ray')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="annotationtest",
            name="selected_expertise",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full expertise selection data from frontend",
            ),
        ),
        migrations.CreateModel(
            name="ExpertiseSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "template_folder",
                    models.CharField(
                        blank=True,
                        help_text="Subfolder name (e.g., 'object-detection-with-bounding-boxes')",
                        max_length=100,
                    ),
                ),
                (
                    "requires_certification",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this specialization requires external certification proof",
                    ),
                ),
                (
                    "certification_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for certification upload/verification",
                    ),
                ),
                (
                    "min_test_questions",
                    models.IntegerField(
                        default=10, help_text="Minimum questions for qualification test"
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70, help_text="Minimum score (%) to pass qualification"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="annotators.expertisecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expertise Specialization",
                "verbose_name_plural": "Expertise Specializations",
                "db_table": "expertise_specialization",
                "ordering": ["category", "display_order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="AnnotatorExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed"),
                            ("testing", "Taking Test"),
                            ("verified", "Verified"),
                            ("failed", "Failed Test"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="claimed",
                        max_length=20,
                    ),
                ),
                ("test_attempts", models.IntegerField(default=0)),
                (
                    "last_test_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When certification expires (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "certification_url",
                    models.URLField(
                        blank=True, help_text="Link to uploaded certification document"
                    ),
                ),
                ("certification_verified", models.BooleanField(default=False)),
                ("tasks_completed", models.IntegerField(default=0)),
                (
                    "accuracy_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "average_time_per_task",
                    models.IntegerField(default=0, help_text="Seconds"),
                ),
                (
                    "self_rating",
                    models.IntegerField(
                        default=5, help_text="Self-rated expertise (1-10)"
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(
                        default=0, help_text="Years of experience in this area"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional info from annotator"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_profiles",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "certification_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_expertise",
                        to="annotators.expertisecategory",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific sub-expertise",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotator_expertise",
                        to="annotators.expertisespecialization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotator Expertise",
                "verbose_name_plural": "Annotator Expertise",
                "db_table": "annotator_expertise",
            },
        ),
        migrations.CreateModel(
            name="ExpertiseTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("multi_select", "Multiple Select"),
                            ("true_false", "True/False"),
                            ("image_label", "Image Labeling"),
                            ("text_annotation", "Text Annotation"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_image_url",
                    models.URLField(
                        blank=True, help_text="URL to image for image-based questions"
                    ),
                ),
                (
                    "question_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional question data (e.g., annotation config)",
                    ),
                ),
                (
                    "options",
                    models.JSONField(default=list, help_text="List of answer options"),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        help_text="Correct answer(s) - index for MCQ, list for multi-select, ground truth for annotations"
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                (
                    "partial_credit",
                    models.BooleanField(
                        default=False,
                        help_text="Allow partial credit for partially correct answers",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation shown after test submission"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="annotators.expertisecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, question only applies to this specialization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="annotators.expertisespecialization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expertise Test Question",
                "verbose_name_plural": "Expertise Test Questions",
                "db_table": "expertise_test_question",
                "ordering": ["category", "specialization", "difficulty", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExpertiseTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="Map of question_id to answer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("max_score", models.IntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "results_breakdown",
                    models.JSONField(default=dict, help_text="Per-question results"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        default=30, help_text="Time limit for the test"
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_tests",
                        to="annotators.annotatorprofile",
                    ),
                ),
                (
                    "expertise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="annotators.annotatorexpertise",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="test_instances",
                        to="annotators.expertisetestquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expertise Test",
                "verbose_name_plural": "Expertise Tests",
                "db_table": "expertise_test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["annotator", "status"], name="annotator_e_annotat_7c6da8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["category", "status"], name="annotator_e_categor_e79415_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["specialization", "status"],
                name="annotator_e_special_d935da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["status", "verified_at"], name="annotator_e_status_3b5e21_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annotatorexpertise",
            unique_together={("annotator", "category", "specialization")},
        ),
        migrations.AddIndex(
            model_name="expertisetestquestion",
            index=models.Index(
                fields=["category", "is_active"], name="expertise_t_categor_4a7cfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertisetestquestion",
            index=models.Index(
                fields=["specialization", "is_active"],
                name="expertise_t_special_a8db8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expertisetestquestion",
            index=models.Index(
                fields=["question_type", "difficulty"],
                name="expertise_t_questio_1adfa8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expertisetest",
            index=models.Index(
                fields=["annotator", "status"], name="expertise_t_annotat_35d64f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertisetest",
            index=models.Index(
                fields=["expertise", "status"], name="expertise_t_experti_d0a75d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expertisetest",
            index=models.Index(
                fields=["status", "created_at"], name="expertise_t_status_93b3d9_idx"
            ),
        ),
    ]
