# Generated by Django 5.1.15 on 2026-02-06 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0019_expertise_system"),
    ]

    operations = [
        # Add badge fields to AnnotatorExpertise
        migrations.AddField(
            model_name="annotatorexpertise",
            name="badge_earned",
            field=models.BooleanField(
                default=False,
                help_text="Whether the badge has been earned for this expertise",
            ),
        ),
        migrations.AddField(
            model_name="annotatorexpertise",
            name="badge_earned_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the badge was earned",
            ),
        ),
        # Add email test token fields
        migrations.AddField(
            model_name="annotatorexpertise",
            name="test_token",
            field=models.UUIDField(
                blank=True,
                null=True,
                unique=True,
                help_text="Token for accessing the expertise test via email link",
            ),
        ),
        migrations.AddField(
            model_name="annotatorexpertise",
            name="test_token_created_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the test token was created",
            ),
        ),
        migrations.AddField(
            model_name="annotatorexpertise",
            name="test_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the test email was sent",
            ),
        ),
        migrations.AddField(
            model_name="annotatorexpertise",
            name="test_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the test email was sent",
            ),
        ),
        # Add indexes for efficient querying
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["badge_earned"],
                name="annotator_e_badge_e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotatorexpertise",
            index=models.Index(
                fields=["test_token"],
                name="annotator_e_test_to_idx",
            ),
        ),
    ]
