# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annotators", "0020_expertise_badges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("tasks_reviewed", models.IntegerField(default=0)),
                ("approvals_count", models.IntegerField(default=0)),
                ("rejections_count", models.IntegerField(default=0)),
                ("corrections_count", models.IntegerField(default=0)),
                ("average_review_time", models.IntegerField(default=0)),
                (
                    "accuracy_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes from admin about this assignment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_expert_expertise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_expertise",
                        to="annotators.expertisecategory",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_profiles",
                        to="annotators.expertprofile",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific sub-expertise",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_expertise",
                        to="annotators.expertisespecialization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Expertise",
                "verbose_name_plural": "Expert Expertise",
                "ordering": ["-assigned_at"],
                "unique_together": {("expert", "category", "specialization")},
            },
        ),
    ]
