# Generated by Django 5.1.15 on 2026-01-13 08:30

import django.db.models.deletion
import jwt_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0002_alter_jwtsettings_api_tokens_enabled_and_more"),
        ("organizations", "0008_organizationmember_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text='A descriptive name for this API key (e.g., "Production SDK", "CI/CD Pipeline")',
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=jwt_auth.models.generate_api_key,
                        help_text="The API key value",
                        max_length=64,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True,
                        help_text="First few characters of the key for identification",
                        max_length=12,
                        verbose_name="key prefix",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of what this API key is used for",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this API key can be used for authentication",
                        verbose_name="active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this API key was last used",
                        null=True,
                        verbose_name="last used at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this API key expires (null = never expires)",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this API key is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="jwt_auth_ap_key_947fa0_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="jwt_auth_ap_user_id_3ef8fa_idx",
                    ),
                ],
            },
        ),
    ]
