# Generated by Django 5.1.14 on 2026-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="published",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="read_time",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(help_text="Markdown content"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=models.URLField(
                blank=True, help_text="URL to cover image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
