# Generated by Django 5.1.14 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assignment_priority",
            field=models.IntegerField(
                default=0,
                help_text="Priority level for task assignment (higher = more urgent)",
                verbose_name="assignment priority",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assignment_strategy",
            field=models.CharField(
                choices=[
                    ("round_robin", "Round Robin"),
                    ("performance", "Performance Based"),
                    ("skill_match", "Skill Matched"),
                    ("consensus", "Consensus Priority"),
                ],
                default="round_robin",
                help_text="Strategy for assigning annotators to this project",
                max_length=20,
                verbose_name="assignment strategy",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="auto_assign",
            field=models.BooleanField(
                default=False,
                help_text="Automatically assign tasks to annotators",
                verbose_name="auto assign",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="max_annotators",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of annotators for this project",
                null=True,
                verbose_name="max annotators",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="min_trust_level",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("junior", "Junior"),
                    ("regular", "Regular"),
                    ("senior", "Senior"),
                    ("expert", "Expert"),
                ],
                default="new",
                help_text="Minimum trust level required for annotators",
                max_length=20,
                verbose_name="minimum trust level",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quality_requirement",
            field=models.FloatField(
                default=0.0,
                help_text="Minimum quality score required (0-1)",
                verbose_name="quality requirement",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="required_overlap",
            field=models.IntegerField(
                default=1,
                help_text="Number of annotators required per task",
                verbose_name="required overlap",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="required_skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required skills for annotators",
                verbose_name="required skills",
            ),
        ),
    ]





