# Generated by Django 5.1.14 on 2025-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_project_assignment_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="auto_assign",
            field=models.BooleanField(
                default=True,
                help_text="Automatically assign tasks to annotators",
                verbose_name="auto assign",
            ),
        ),
    ]





