# Generated by Django 5.1.14 on 2026-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_alter_project_auto_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="required_overlap",
            field=models.IntegerField(
                default=3,
                help_text="Number of annotators required per task (default: 3 for consensus)",
                verbose_name="required overlap",
            ),
        ),
    ]





