# Generated by Django 5.1.15 on 2026-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_add_annotator_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="honeypot_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable honeypot quality control tasks",
                verbose_name="honeypot enabled",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="honeypot_failure_threshold",
            field=models.IntegerField(
                default=3,
                help_text="Max consecutive honeypot failures before suspension",
                verbose_name="honeypot failure threshold",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="honeypot_injection_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Percentage of tasks that are honeypots (0.0-1.0)",
                max_digits=4,
                verbose_name="honeypot injection rate",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="honeypot_min_interval",
            field=models.IntegerField(
                default=5,
                help_text="Minimum tasks between honeypots per annotator",
                verbose_name="honeypot minimum interval",
            ),
        ),
    ]
