# Generated by Django 5.1.14 on 2026-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_honeypot_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="min_annotations_to_start_training",
        ),
        migrations.RemoveField(
            model_name="project",
            name="model_version",
        ),
    ]
