# Generated by GitHub Copilot
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_remove_project_min_annotations_to_start_training_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_draft",
        ),
    ]
