# Generated by Django - Project expertise requirements migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotators', '0021_expert_expertise'),
        ('projects', '0039_remove_project_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_expertise_category',
            field=models.ForeignKey(
                blank=True,
                help_text='Required expertise category for annotators/experts',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='annotators.expertisecategory',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='required_expertise_specialization',
            field=models.ForeignKey(
                blank=True,
                help_text='Required expertise specialization (more specific than category)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='annotators.expertisespecialization',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='expertise_required',
            field=models.BooleanField(
                default=False,
                help_text='If True, only annotators/experts with matching expertise can be assigned',
                verbose_name='expertise required',
            ),
        ),
    ]
