# Generated by Django 5.1.15 on 2026-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0022_normalize_localfiles_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azureblobimportstorage",
            name="presign_ttl",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Presigned URLs TTL (in minutes)",
                verbose_name="presign_ttl",
            ),
        ),
        migrations.AlterField(
            model_name="gcsimportstorage",
            name="presign_ttl",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Presigned URLs TTL (in minutes)",
                verbose_name="presign_ttl",
            ),
        ),
        migrations.AlterField(
            model_name="s3importstorage",
            name="presign_ttl",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Presigned URLs TTL (in minutes)",
                verbose_name="presign_ttl",
            ),
        ),
    ]
