# Generated by Django 5.1.15 on 2026-01-15 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0037_honeypot_config"),
        ("tasks", "0062_add_annotator_notification"),
        ("users", "0014_user_annotator_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRiskProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="risk_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=0, help_text="Cumulative risk score (0-100+)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        help_text="Current risk classification",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_rules",
                    models.JSONField(
                        default=list,
                        help_text="List of rules that contributed to score",
                    ),
                ),
                (
                    "last_event_at",
                    models.DateTimeField(
                        blank=True, help_text="Time of last telemetry event", null=True
                    ),
                ),
                (
                    "last_violation_at",
                    models.DateTimeField(
                        blank=True, help_text="Time of last rule violation", null=True
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False, help_text="Account frozen due to high risk"
                    ),
                ),
                (
                    "frozen_at",
                    models.DateTimeField(
                        blank=True, help_text="When account was frozen", null=True
                    ),
                ),
                (
                    "frozen_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for freezing"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "telemetry_user_risk_profile",
            },
        ),
        migrations.CreateModel(
            name="RuleViolation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the violated rule",
                        max_length=100,
                    ),
                ),
                (
                    "risk_points",
                    models.IntegerField(help_text="Points added to risk score"),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        default=dict, help_text="Data that triggered the rule"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Action taken (if any)",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "telemetry_rule_violation",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("event", "Telemetry Event"),
                            ("violation", "Rule Violation"),
                            ("action", "Action Taken"),
                            ("freeze", "Account Frozen"),
                            ("unfreeze", "Account Unfrozen"),
                            ("alert", "Admin Alert"),
                            ("export", "Data Export"),
                            ("access", "Data Access"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "payload_encrypted",
                    models.TextField(
                        blank=True, default="", help_text="Encrypted JSON payload"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Human-readable summary (non-sensitive)"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Admin who took action (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "telemetry_security_audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("mouse_entropy", "Mouse Movement Entropy"),
                            ("click", "Click Event"),
                            ("scroll", "Scroll Event"),
                            ("zoom", "Zoom Event"),
                            ("dwell", "Image Dwell Time"),
                            ("focus", "Tab Focus"),
                            ("blur", "Tab Blur"),
                            ("devtools", "DevTools Detected"),
                            ("copy", "Copy Attempt"),
                            ("printscreen", "Print Screen Key"),
                            ("contextmenu", "Context Menu Attempt"),
                            ("dragstart", "Drag Attempt"),
                            ("vm_detected", "VM/RDP Detected"),
                            ("headless", "Headless Browser Detected"),
                            ("multi_monitor", "Multiple Monitors Detected"),
                            ("keyboard_shortcut", "Blocked Keyboard Shortcut"),
                            ("session_start", "Session Started"),
                            ("session_end", "Session Ended"),
                        ],
                        db_index=True,
                        help_text="Type of behavior event",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        default=dict,
                        help_text="Event-specific data (e.g., zoom level, dwell time ms)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the event occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="Browser user agent string"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Browser session identifier",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemetry_events",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task being viewed when event occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemetry_events",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who generated this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "telemetry_event",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="telemetry_e_user_id_a277e2_idx",
                    ),
                    models.Index(
                        fields=["user", "event_type", "timestamp"],
                        name="telemetry_e_user_id_945f09_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="telemetry_e_session_3ddcf6_idx",
                    ),
                ],
            },
        ),
    ]
