# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .edition_enum import EditionEnum
import pydantic
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class VersionResponse(UncheckedBaseModel):
    backend: typing.Optional[typing.Any] = None
    dm2: typing.Optional[typing.Any] = None
    edition: EditionEnum = pydantic.Field()
    """
    Synapse edition (Community or Enterprise)
    
    * `Community` - Community
    * `Enterprise` - Enterprise
    """

    synapse_converter: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="synapse-converter")
    ] = None
    synapse_frontend: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="synapse-frontend")
    ] = None
    synapse_os_backend: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="synapse-os-backend")
    ] = None
    synapse_os_package: typing_extensions.Annotated[
        typing.Optional[typing.Any], FieldMetadata(alias="synapse-os-package")
    ] = None
    sf: typing.Optional[typing.Any] = None
    release: str = pydantic.Field()
    """
    Current release version of Synapse
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
