# Generated by Django 5.1.14 on 2025-12-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_annotator",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has annotator privileges.",
                verbose_name="annotator role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has client privileges.",
                verbose_name="client role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_expert",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has expert privileges for quality review.",
                verbose_name="expert role",
            ),
        ),
    ]





