# Generated by Django 5.1.14 on 2025-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_is_annotator_user_is_client_user_is_expert"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="annotator_status",
            field=models.CharField(
                default="pending_verification",
                help_text="Status of annotator in the qualification workflow",
                max_length=32,
                verbose_name="annotator status",
            ),
        ),
    ]





